# Generated by Django 5.2.3 on 2025-06-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emai',
            new_name='email',
        ),
    ]
